export const TLD = [
  { tld: "al", country: "albania" },
  { tld: "ad", country: "andorra" },
  { tld: "am", country: "armenia" },
  { tld: "at", country: "austria" },
  { tld: "az", country: "azerbaijan" },
  { tld: "by", country: "belarus" },
  { tld: "be", country: "belgium" },
  { tld: "ba", country: "bosnia and herzegovina" },
  { tld: "bg", country: "bulgaria" },
  { tld: "hr", country: "croatia" },
  { tld: "cy", country: "cyprus" },
  { tld: "cz", country: "czech republic" },
  { tld: "dk", country: "denmark" },
  { tld: "gb-eng", country: "england" },
  { tld: "ee", country: "estonia" },
  { tld: "fo", country: "faroe islands" },
  { tld: "fi", country: "finland" },
  { tld: "fr", country: "france" },
  { tld: "ge", country: "georgia" },
  { tld: "de", country: "germany" },
  { tld: "gi", country: "gibraltar" },
  { tld: "gr", country: "greece" },
  { tld: "gl", country: "greenland" },
  { tld: "hu", country: "hungary" },
  { tld: "is", country: "iceland" },
  { tld: "ie", country: "ireland" },
  { tld: "it", country: "italy" },
  { tld: "kz", country: "kazakhstan" },
  { tld: "xk", country: "kosovo" },
  { tld: "kg", country: "kyrgyzstan" },
  { tld: "lv", country: "latvia" },
  { tld: "li", country: "liechtenstein" },
  { tld: "lt", country: "lithuania" },
  { tld: "lu", country: "luxembourg" },
  { tld: "mk", country: "macedonia" },
  { tld: "mt", country: "malta" },
  { tld: "md", country: "moldova" },
  { tld: "mc", country: "monaco" },
  { tld: "me", country: "montenegro" },
  { tld: "nl", country: "netherlands" },
  { tld: "gb-nir", country: "northern ireland" },
  { tld: "no", country: "norway" },
  { tld: "pl", country: "poland" },
  { tld: "pt", country: "portugal" },
  { tld: "ro", country: "romania" },
  { tld: "ru", country: "russian federation" },
  { tld: "sm", country: "san marino" },
  { tld: "gb-sct", country: "scotland" },
  { tld: "rs", country: "serbia" },
  { tld: "sk", country: "slovakia" },
  { tld: "si", country: "slovenia" },
  { tld: "es", country: "spain" },
  { tld: "se", country: "sweden" },
  { tld: "ch", country: "switzerland" },
  { tld: "tj", country: "tajikistan" },
  { tld: "tr", country: "turkey" },
  { tld: "tm", country: "turkmenistan" },
  { tld: "ua", country: "ukraine" },
  { tld: "uz", country: "uzbekistan" },
  { tld: "gb-wls", country: "wales" }
];
